abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/draft/',
                    manage.DraftExtensionView.as_view(),
                    name='draft',
                ),
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/delete/',
                    manage.DeleteExtensionView.as_view(),
                    name='delete',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
                path('<slug:slug>/', manage.ExtensionDetailView.as_view(), name='detail'),
            ],
        ),
    ),
]

notifications/urls.py
from django.urls import path, include

import notifications.views as views

app_name = 'notifications'
urlpatterns = [
    path(
        'notifications/',
        include(
            [
                path('', views.NotificationsView.as_view(), name='notifications'),
                path(
                    'mark-read-all/',
                    views.MarkReadAllView.as_view(),
                    name='notifications-mark-read-all',
                ),
                path(
                    '<int:pk>/mark-read/',
                    views.MarkReadView.as_view(),
                    name='notifications-mark-read',
                ),
            ],
        ),
    ),
]

reviewers/urls.py
from django.urls import path

from reviewers import views

app_name = 'reviewers'
urlpatterns = [
    path('approval-queue/', views.ApprovalQueueView.as_view(), name='approval-queue'),
    path(
        'approval-queue/<slug:slug>/',
        views.ExtensionsApprovalDetailView.as_view(),
        name='approval-detail',
    ),
    path(
        'approval-queue/<slug:slug>/comment',
        views.ExtensionsApprovalFormView.as_view(),
        name='approval-comment',
    ),
]

users/urls.py
from django.urls import path, include

from users.views.webhooks import user_modified_webhook
import users.views.settings as settings

app_name = 'users'
urlpatterns = [
    path('webhooks/user-modified/', user_modified_webhook, name='webhook-user-modified'),
    path(
        'settings/',
        include(
            [
                path('profile/', settings.ProfileView.as_view(), name='my-profile'),
                path(
                    'profile/subscribe-notification-emails/',
                    settings.SubscribeNotificationEmailsView.as_view(),
                    name='subscribe-notification-emails',
                ),
                path('delete/', settings.DeleteView.as_view(), name='my-profile-delete'),
            ]
        ),
    ),
]

common/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""

    template_name = 'common/error.html'
    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        # TODO: respond as JSON when this is an XHR.
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view
        context = self.get_context_data(**kwargs)
        context['status'] = self.status
        response = self.render_to_response(context)
        response.status_code = self.status
        return response

common/templates/common/base.html
{% load common %}
{% load pipeline %}
{% load static %}
{% load i18n %}
{% load waffle_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block page_title %}Free and Open Source Extensions{% endblock page_title %} &mdash; Blender Extensions</title>

    {% block head_favicon %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'icons/favicon.svg' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    {% endblock head_favicon %}

    {% block meta %}
      {% include 'common/components/meta.html' %}
    {% endblock meta %}

    {% stylesheet 'common' %}

    {% block head_style_extras %}
    {% endblock head_style_extras %}

    <script defer data-domain="extensions.blender.org" src="https://analytics.blender.org/js/script.outbound-links.file-downloads.tagged-events.js"></script>
  </head>

  <body class="has-global-bar">
    {% switch "is_alpha" %}
    <div class="site-announcement-alpha">
      This platform is currently in alpha.
      <a class="text-underline" href="https://projects.blender.org/infrastructure/extensions-website/issues" target="_blank">Please report any issues you may find</a>, thanks! <a class="text-underline" href="https://devtalk.blender.org/tag/extensions" target="_blank">Learn more</a>
    </div>
    {% else %}
      {% switch "is_beta" %}
    <div class="site-announcement-beta">
      The website will be officially released together with Blender 4.2.
      Meanwhile you can use the extensions with a <a class="text-underline" href="https://builder.blender.org/" target="_blank"> daily build</a> of Blender. <a class="text-underline" href="https://devtalk.blender.org/tag/extensions" target="_blank">Learn more</a>
    </div>
      {% endswitch %}
    {% endswitch %}
    {% if request.user.is_staff %}
    <div class="whoosh-container">
      <a href="{% url 'admin:index' %}" title='Admin' class="whoosh">
        <i class="i-settings"></i>
      </a>
      {% block admin_button_page %}{% endblock %}
    </div>
    {% endif %}
    <div class="nav-global">
      <div class="nav-global-container">
        <nav>
          <div class="site-beta-logo-container">
            <a href="/" class="nav-global-logo{% if request.get_full_path == '/' %} is-active{% endif %}">
              <svg fill-rule="nonzero" viewBox="0 0 200 162.05">
                <path
                  d="M61.1 104.56c.05 2.6.88 7.66 2.12 11.61a61.27 61.27 0 0 0 13.24 22.92 68.39 68.39 0 0 0 23.17 16.64 74.46 74.46 0 0 0 30.42 6.32 74.52 74.52 0 0 0 30.4-6.42 68.87 68.87 0 0 0 23.15-16.7 61.79 61.79 0 0 0 13.23-22.97 58.06 58.06 0 0 0 2.07-25.55 59.18 59.18 0 0 0-8.44-23.1 64.45 64.45 0 0 0-15.4-16.98h.02L112.76 2.46l-.16-.12c-4.09-3.14-10.96-3.13-15.46.02-4.55 3.18-5.07 8.44-1.02 11.75l-.02.02 26 21.14-79.23.08h-.1c-6.55.01-12.85 4.3-14.1 9.74-1.27 5.53 3.17 10.11 9.98 10.14v.02l40.15-.07-71.66 55-.27.2c-6.76 5.18-8.94 13.78-4.69 19.23 4.32 5.54 13.51 5.55 20.34.03l39.1-32s-.56 4.32-.52 6.91zm100.49 14.47c-8.06 8.2-19.34 12.86-31.54 12.89-12.23.02-23.5-4.6-31.57-12.79-3.93-4-6.83-8.59-8.61-13.48a35.57 35.57 0 0 1 2.34-29.25 39.1 39.1 0 0 1 9.58-11.4 44.68 44.68 0 0 1 28.24-9.85 44.59 44.59 0 0 1 28.24 9.77 38.94 38.94 0 0 1 9.58 11.36 35.58 35.58 0 0 1 4.33 14.18 35.1 35.1 0 0 1-1.98 15.05 37.7 37.7 0 0 1-8.61 13.52zm-57.6-27.91a23.55 23.55 0 0 1 8.55-16.68 28.45 28.45 0 0 1 18.39-6.57 28.5 28.5 0 0 1 18.38 6.57 23.57 23.57 0 0 1 8.55 16.67c.37 6.83-2.37 13.19-7.2 17.9a28.18 28.18 0 0 1-19.73 7.79c-7.83 0-14.84-3-19.75-7.8a23.13 23.13 0 0 1-7.19-17.88z" />
                <strong>Extensions</strong>
              </svg>
            </a>
            {% switch "is_alpha" %}
              <div class="site-release-badge">alpha</div>
            {% else %}
              {% switch "is_beta" %}
            <div class="site-release-badge is-beta">beta</div>
              {% endswitch %}
            {% endswitch %}
          </div>

          <button class="nav-global-logo js-dropdown-toggle" data-toggle-menu-id="nav-global-nav-links">
            <svg fill-rule="nonzero" viewBox="0 0 850.2 162.05">
              <path
                d="M61.1 104.56c.05 2.6.88 7.66 2.12 11.61a61.27 61.27 0 0 0 13.24 22.92 68.39 68.39 0 0 0 23.17 16.64 74.46 74.46 0 0 0 30.42 6.32 74.52 74.52 0 0 0 30.4-6.42 68.87 68.87 0 0 0 23.15-16.7 61.79 61.79 0 0 0 13.23-22.97 58.06 58.06 0 0 0 2.07-25.55 59.18 59.18 0 0 0-8.44-23.1 64.45 64.45 0 0 0-15.4-16.98h.02L112.76 2.46l-.16-.12c-4.09-3.14-10.96-3.13-15.46.02-4.55 3.18-5.07 8.44-1.02 11.75l-.02.02 26 21.14-79.23.08h-.1c-6.55.01-12.85 4.3-14.1 9.74-1.27 5.53 3.17 10.11 9.98 10.14v.02l40.15-.07-71.66 55-.27.2c-6.76 5.18-8.94 13.78-4.69 19.23 4.32 5.54 13.51 5.55 20.34.03l39.1-32s-.56 4.32-.52 6.91zm100.49 14.47c-8.06 8.2-19.34 12.86-31.54 12.89-12.23.02-23.5-4.6-31.57-12.79-3.93-4-6.83-8.59-8.61-13.48a35.57 35.57 0 0 1 2.34-29.25 39.1 39.1 0 0 1 9.58-11.4 44.68 44.68 0 0 1 28.24-9.85 44.59 44.59 0 0 1 28.24 9.77 38.94 38.94 0 0 1 9.58 11.36 35.58 35.58 0 0 1 4.33 14.18 35.1 35.1 0 0 1-1.98 15.05 37.7 37.7 0 0 1-8.61 13.52zm-57.6-27.91a23.55 23.55 0 0 1 8.55-16.68 28.45 28.45 0 0 1 18.39-6.57 28.5 28.5 0 0 1 18.38 6.57 23.57 23.57 0 0 1 8.55 16.67c.37 6.83-2.37 13.19-7.2 17.9a28.18 28.18 0 0 1-19.73 7.79c-7.83 0-14.84-3-19.75-7.8a23.13 23.13 0 0 1-7.19-17.88z" />
            </svg>
            <svg class="nav-global-icon nav-global-icon-dropdown-toggle" height="100px" width="100px" viewBox="0 0 1000 1000">
              <path
                d="m 206.53824,376.41174 a 42,42 0 0 1 71,-29 l 221,220 220,-220 a 42,42 0 1 1 59,59 l -250,250 a 42,42 0 0 1 -59,0 l -250,-250 a 42,42 0 0 1 -12,-30 z" />
            </svg>
          </button>

          <ul class="nav-global-nav-links nav-global-dropdown js-dropdown-menu" id="nav-global-nav-links">
            <li>
              <a href="{% url 'extensions:by-type' type_slug='add-ons' %}" class="{% if '/add-ons/' in request.get_full_path %}is-active{% endif %}">
                Add-ons
              </a>
            </li>
            <li>
              <a href="{% url 'extensions:by-type' type_slug='themes' %}" class="{% if '/themes/' in request.get_full_path %}is-active{% endif %}">
                Themes
              </a>
            </li>
            <li>
              <a href="{% url 'reviewers:approval-queue' %}" class="{% if '/approval-queue/' in request.get_full_path %}is-active{% endif %}">
                Approval Queue
              </a>
            </li>
            <li>
              <a href="{% url 'flatpage-about' %}" class="{% if '/about/' in request.get_full_path %}is-active{% endif %}">
                About
              </a>
            </li>
          </ul>

          <ul class="nav-global-links-right">
            <li>
              <search>
                <form action="{% url "extensions:search" %}" method="GET" class="navbar-search">
                  <input type="text" name="q" class="form-control"
                    {% if request.GET.q %}
                      value="{{ request.GET.q }}"
                    {% else %}
                      placeholder="Search..."
                    {% endif %}
                    aria-label="Search"
                    aria-describedby="nav-search-button">
                    <button type="submit" id="nav-search-button">
                      <i class="i-search"></i>
                    </button>
                </form>
              </search>
            </li>

            {% block nav-upload %}
            <li class="me-2">
              <a href="{% url 'extensions:submit' %}" class="btn btn-primary">
                <i class="i-upload"></i>
                <span>Upload Extension</span>
              </a>
            </li>
            {% endblock nav-upload %}

            {% if user.is_authenticated %}
              <a href="{% url 'notifications:notifications' %}">
                <i class="i-bell {% if user|unread_notification_count %}text-primary{% endif %}"></i>
              </a>
              <li class="nav-item dropdown">
                <button id="navbarDropdown" aria-expanded="false" aria-haspopup="true" data-toggle-menu-id="nav-account-dropdown" role="button" class="nav-link dropdown-toggle js-dropdown-toggle">
                  <i class="i-user"></i>
                  <i class="i-chevron-down"></i>
                </button>
                <ul id="nav-account-dropdown" aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right js-dropdown-menu">
                  {% if user.is_staff %}
                  <li>
                    <a href="{% url 'admin:index' %}" class="dropdown-item is-admin">
                      <i class="i-coffee"></i> Admin
                    </a>
                  </li>
                  {% endif %}
                  {% if user.is_moderator %}
                  <li>
                    <a href="{% url 'abuse:report-list' %}" class="dropdown-item">
                      <i class="i-shield"></i> {% trans "Abuse Reports" %}
                    </a>
                  </li>
                  <li class="dropdown-divider"></li>
                  {% endif %}

                  <li>
                    <a href="{% url 'extensions:manage-list' %}" class="dropdown-item">
                      <i class="i-puzzle"></i> {% trans 'My Extensions' %}
                    </a>
                  </li>

                  <li>
                    <a href="{% url 'users:my-profile' %}" class="dropdown-item">
                      <i class="i-user"></i> {% trans 'My Profile' %}
                    </a>
                  </li>

                  <li class="dropdown-divider"></li>

                  <li>
                    <a href="https://projects.blender.org/infrastructure/extensions-website/issues" class="dropdown-item">
                      <i class="i-alert-triangle"></i> {% trans 'Report Problem' %}
                    </a>
                  </li>

                  <li class="dropdown-divider"></li>

                  <li>
                    <a href="{% url 'oauth:logout' %}" class="dropdown-item">
                      <i class="i-log-out"></i> {% trans 'Log out' %}
                    </a>
                  </li>

                  {# For exiting a "Login-As" switcheroo #}
                  {% if is_impersonated_session %}
                    {% with warn="(!) You are currently using login-as to impersonate someone else's session" %}
                    <li>
                      <a class="dropdown-item text-warning" title="{{ warn }}" href="{% url 'loginas-logout' %}">
                        <i class="i-log-out"></i>
                        {% trans 'Switch Back' %}
                      </a>
                    </li>
                    {% endwith %}
                  {% endif %}
                </ul>
              </li>
            {% elif page_id != 'login' and page_id != 'register' %}
              {% include "common/components/nav_item.html" with name="oauth:login" title="Sign in" %}
            {% endif %}

            <li>
              <div class="nav-global-apps-dropdown-container">
                <button class="js-dropdown-toggle" data-toggle-menu-id="nav-global-apps-menu">
                  <svg class="nav-global-icon" height="100px" width="100px" viewBox="0 0 1000 1000">
                    <path
                      d="m 150.5,899 a 50,50 0 0 1 -49,-50 V 749 a 50,50 0 0 1 49,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 749 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 749 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m -598,-299 a 50,50 0 0 1 -49,-50 V 450 a 50,50 0 0 1 49,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 450 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 450 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m -598,-299 a 50,50 0 0 1 -49,-50 V 151 a 50,50 0 0 1 49,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 151 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z m 299,0 a 50,50 0 0 1 -50,-50 V 151 a 50,50 0 0 1 50,-50 h 100 a 50,50 0 0 1 50,50 v 100 a 50,50 0 0 1 -50,50 z" />
                  </svg>
                </button>

                {% include '_navbar_global_dropdown.html' %}
              </div>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <div class="navdrawer-offset">
      {% block breadcrumbs %}{% endblock breadcrumbs %}

      {% if messages %}
        {% for message in messages %}
        <div role="alert" class="alert show text-center {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          <div class="container">
            {{ message }}
          </div>
        </div>
        {% endfor %}
      {% endif %}

      {% block container_main %}
      <div class="container-main">
        {% block hero %}
        {% endblock hero %}

        <div class="container">
          {% block content %}{% endblock content %}
        </div>
      </div>
      {% endblock container_main %}
    </div>

    {% block footer %}
      {% include "_footer.html" %}
    {% endblock footer %}

    {% javascript "common" %}
    {% block scripts %}{% endblock scripts %}

  </body>
</html>

common/templates/common/error.html
{% extends "common/base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-6 mx-auto text-center">
    <div class="box">
      <h3>
        {{ status }}
        {% if status == 400 %}
          Bad Request
        {% elif status == 401 %}
          Unauthorized
        {% elif status == 403 %}
          Forbidden
        {% elif status == 404 %}
          Page Not Found
        {% elif status == 405 %}
          Method Not Allowed
        {% elif status >= 500 %}
          Server Error
        {% else %}
          Houston, we have a problem.
        {% endif %}
      </h3>
      <p class="m-0">
        {% if status == 400 %}
        {% elif status == 401 %}
          You are not authorized to visit this page.
        {% elif status == 403 %}
          Access denied.
        {% elif status == 404 %}
          The page you requested does not exist.
        {% elif status == 405 %}
        {% elif status >= 500 %}
        {% endif %}
      </p>
    </div>
  </div>
</div>
{% endblock content %}

common/templates/common/paginator.html
{% load i18n common %}
{% if num_pages > 1 %}
  <ol class="pagination">
    {% if pager.has_previous %}
      <li>
        <a rel="prev" href="{{ pager.url|urlparams:pager.previous_page_number }}">
          {{ _('Prev') }}
        </a>
      </li>
    {% endif %}
    {% if pager.dotted_lower %}
      <li><a href="{{ pager.url|urlparams:1 }}">{{ 1 }}</a></li>
      <li class="skip">&hellip;</li>
    {% endif %}
    {% for x in pager.page_range %}
      <li {{ x|class_selected:pager.number }}>
        <a href="{{ pager.url|urlparams:x }}">{{ x }}</a>
      </li>
    {% endfor %}
    {% if pager.dotted_upper %}
      <li class="skip">&hellip;</li>
      <li><a href="{{ pager.url|urlparams:num_pages }}">{{ num_pages }}</a></li>
    {% endif %}
    {% if pager.has_next %}
      <li>
        <a rel="next" href="{{ pager.url|urlparams:pager.next_page_number }}">
          {{ _('Next') }}
        </a>
      </li>
    {% endif %}
  </ol>
  <div class="num-results">
    {% blocktranslate with begin=pager.start_index end=pager.end_index count=count %}
      Results <strong>{{ begin }}</strong>&ndash;<strong>{{ end }}</strong>
      of <strong>{{ count }}</strong>
    {% endblocktranslate %}
  </div>
{% endif %}