abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/', views.ReportList.as_view(), name='report-list'),
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
                path(
                    '<slug:slug>/<str:version>/<int:rating>/report/',
                    views.ReportRatingView.as_view(),
                    name='report-ratings',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('', include('notifications.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns = [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/draft/',
                    manage.DraftExtensionView.as_view(),
                    name='draft',
                ),
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/delete/',
                    manage.DeleteExtensionView.as_view(),
                    name='delete',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
                path('<slug:slug>/', manage.ExtensionDetailView.as_view(), name='detail'),
            ],
        ),
    ),
]

abuse/models.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.gis.geoip2 import GeoIP2, GeoIP2Exception
from django.core.validators import validate_ipv46_address
from django.db import models
from django.urls import reverse

from extended_choices import Choices
from geoip2.errors import GeoIP2Error

from constants.base import ABUSE_TYPE, ABUSE_TYPE_EXTENSION, ABUSE_TYPE_RATING
from common.model_mixins import CreatedModifiedMixin, TrackChangesMixin
import extensions.fields

User = get_user_model()


class AbuseReport(CreatedModifiedMixin, TrackChangesMixin, models.Model):
    TYPE = ABUSE_TYPE

    REASONS = Choices(
        ('OTHER', 127, 'Other'),
        ('DAMAGE', 1, 'Damages computer and/or data'),
        ('SPAM', 2, 'Creates spam or advertising'),
        ('BROKEN', 3, "Doesn't work, breaks Blender, or slows it down"),
        ('POLICY', 4, 'Hateful, violent, or illegal content'),
        ('DECEPTIVE', 5, "Pretends to be something it's not"),
    )

    STATUSES = Choices(
        ('UNTRIAGED', 1, 'Untriaged'),
        ('VALID', 2, 'Valid'),
        ('SUSPICIOUS', 3, 'Suspicious'),
    )

    # NULL if the reporter is anonymous.
    # FIXME? make non-null
    reporter = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='abuse_reported',
        on_delete=models.SET_NULL,
    )
    # An abuse report can be for an extension or a user.
    # If user is set then extension should be null.
    # If extension is null then user should be set.
    user = models.ForeignKey(
        User, null=True, related_name='abuse_reports', on_delete=models.SET_NULL
    )
    extension = models.ForeignKey(
        'extensions.Extension', blank=True, null=True, on_delete=models.CASCADE
    )
    extension_version = extensions.fields.VersionStringField(max_length=64, null=True, blank=True)
    rating = models.ForeignKey('ratings.Rating', blank=True, null=True, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    reason = models.PositiveSmallIntegerField(
        default=REASONS[0][1], choices=REASONS.choices, blank=False, null=False
    )
    version = extensions.fields.VersionStringField(
        max_length=64,
        null=True,
        blank=True,
        help_text=('Version of Blender affected by this report, if applicable.'),
    )
    type = models.PositiveSmallIntegerField(
        default=ABUSE_TYPE_EXTENSION, choices=TYPE.choices, blank=False, null=False
    )

    status = models.PositiveSmallIntegerField(default=STATUSES.UNTRIAGED, choices=STATUSES.choices)

    @classmethod
    def lookup_country_code_from_ip(cls, ip):
        try:
            # Early check to avoid initializing GeoIP2 on invalid addresses
            if not ip:
                raise forms.ValidationError('No IP')
            validate_ipv46_address(ip)
            geoip = GeoIP2()
            value = geoip.country_code(ip)
        # Annoyingly, we have to catch both django's GeoIP2Exception (setup
        # issue) and geoip2's GeoIP2Error (lookup issue)
        except (forms.ValidationError, GeoIP2Exception, GeoIP2Error):
            value = ''
        return value

    @property
    def name(self) -> str:
        return self.extension.name if self.extension else self.user

    def __str__(self) -> str:
        return f'Abuse Report for {self.type} {self.name}'

    @classmethod
    def exists(cls, user_id: int, extension_id: int, rating_id: int = None) -> bool:
        if rating_id is None:
            return cls.objects.filter(
                reporter_id=user_id, extension_id=extension_id, type=ABUSE_TYPE_EXTENSION
            ).exists()
        return cls.objects.filter(
            reporter_id=user_id,
            extension_id=extension_id,
            rating_id=rating_id,
            type=ABUSE_TYPE_RATING,
        ).exists()

    def get_absolute_url(self):
        return reverse('abuse:view-report', args=[self.pk])

    def get_admin_url(self):
        return reverse('admin:abuse_abusereport_change', args=[self.pk])

extensions/views/api.py
import logging

from rest_framework.response import Response
from rest_framework import serializers
from rest_framework.views import APIView
from drf_spectacular.utils import OpenApiParameter, extend_schema
from django.core.exceptions import ValidationError

from common.compare import is_in_version_range, version
from extensions.models import Extension
from extensions.utils import clean_json_dictionary_from_optional_fields


from constants.base import (
    EXTENSION_TYPE_SLUGS_SINGULAR,
)

log = logging.getLogger(__name__)


class ListedExtensionsSerializer(serializers.ModelSerializer):
    error_messages = {
        "invalid_version": "Invalid version: use full semantic versioning like 4.2.0."
    }

    class Meta:
        model = Extension
        fields = ()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.blender_version = kwargs.pop('blender_version', None)
        self._validate()
        super().__init__(*args, **kwargs)

    def _validate(self):
        if self.blender_version is None:
            return
        try:
            version(self.blender_version)
        except ValidationError:
            self.fail('invalid_version')

    def to_representation(self, instance):
        matching_version = None
        # avoid triggering additional db queries, reuse the prefetched queryset
        versions = [
            v
            for v in instance.versions.all()
            if v.file and v.file.status in instance.valid_file_statuses
        ]
        if not versions:
            return None
        versions = sorted(versions, key=lambda v: v.date_created, reverse=True)
        if self.blender_version:
            for v in versions:
                if is_in_version_range(
                    self.blender_version,
                    v.blender_version_min,
                    v.blender_version_max,
                ):
                    matching_version = v
                    break
        else:
            # same as latest_version, but without triggering a new queryset
            matching_version = versions[0]

        if not matching_version:
            return None

        data = {
            'id': instance.extension_id,
            'schema_version': matching_version.schema_version,
            'name': instance.name,
            'version': matching_version.version,
            'tagline': matching_version.tagline,
            'archive_hash': matching_version.file.original_hash,
            'archive_size': matching_version.file.size_bytes,
            'archive_url': self.request.build_absolute_uri(matching_version.download_url),
            'type': EXTENSION_TYPE_SLUGS_SINGULAR.get(instance.type),
            'blender_version_min': matching_version.blender_version_min,
            'blender_version_max': matching_version.blender_version_max,
            'website': self.request.build_absolute_uri(instance.get_absolute_url()),
            # avoid triggering additional db queries, reuse the prefetched queryset
            'maintainer': str(instance.authors.all()[0]),
            'license': [license_iter.slug for license_iter in matching_version.licenses.all()],
            'permissions': [permission.slug for permission in matching_version.permissions.all()],
            # TODO: handle copyright
            'tags': [str(tag) for tag in matching_version.tags.all()],
        }

        return clean_json_dictionary_from_optional_fields(data)


class ExtensionsAPIView(APIView):
    serializer_class = ListedExtensionsSerializer

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name="blender_version",
                description=("Blender version to check for compatibility"),
                type=str,
            )
        ]
    )
    def get(self, request):
        blender_version = request.GET.get('blender_version')
        qs = Extension.objects.listed.prefetch_related(
            'authors',
            'versions',
            'versions__file',
            'versions__licenses',
            'versions__permissions',
            'versions__tags',
        ).all()
        serializer = self.serializer_class(
            qs, blender_version=blender_version, request=request, many=True
        )
        data = [e for e in serializer.data if e is not None]
        return Response(
            {
                # TODO implement extension blocking by moderators
                'blocklist': [],
                'data': data,
                'version': 'v1',
            }
        )

extensions/views/mixins.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404

from extensions.models import Extension
from files.models import File


class OwnsFileMixin(UserPassesTestMixin):
    def dispatch(self, *args, **kwargs):
        self.file = get_object_or_404(File, pk=self.kwargs['pk'])
        self.extension = self._get_extension()
        return super().dispatch(*args, **kwargs)

    def test_func(self) -> bool:
        return self.file.user == self.request.user


class ExtensionQuerysetMixin:
    """Add reusable methods to class-based views handling Extensions."""

    def get_extension_queryset(self):
        """Return queryset with unlisted add-ons for logged in users under certain conditions."""
        if self.request.user.is_staff:
            return Extension.objects.all()
        if self.request.user.is_authenticated:
            return Extension.objects.listed_or_authored_by(user_id=self.request.user.pk)
        return Extension.objects.listed


class MaintainedExtensionMixin:
    """Fetch an extension by slug if current user is a maintainer."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(
            Extension.objects.authored_by(user_id=self.request.user.pk),
            slug=self.kwargs['slug'],
        )
        return super().dispatch(*args, **kwargs)


class ListedExtensionMixin:
    """Fetch a publicly listed extension by slug in the URL before dispatching the view."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(Extension.objects.listed, slug=self.kwargs['slug'])
        return super().dispatch(*args, **kwargs)


class ExtensionMixin:
    """Fetch an extension by slug in the URL before dispatching the view."""

    def dispatch(self, *args, **kwargs):
        self.extension = get_object_or_404(Extension, slug=self.kwargs['slug'])
        return super().dispatch(*args, **kwargs)


class DraftVersionMixin:
    """Fetch the version object which is being edited as a draft."""

    def dispatch(self, *args, **kwargs):
        self.version = self.extension.versions.first()
        return super().dispatch(*args, **kwargs)

extensions/templates/extensions/components/authors.html
{# Indentation looks like this so there is no gap between the author name and comma. #}
{% for author in extension.authors.all %}{% if forloop.counter > 1 %},&nbsp;{% endif %}<a href="{% url "extensions:by-author" user_id=author.pk %}" title="{{ author }}">{{ author }}</a>{% endfor %}

extensions/templates/extensions/components/badge_support.html
<a href="{% url "extensions:by-support" support_slug=slug %}" title="Support: {{ name }}"
  class="badge text-decoration-none align-middle {% if not small %}px-3 py-2 my-1{% endif %} badge-dark{#% if slug == 'official' %}primary{% elif slug == 'community' %}success{% else %}warning{% endif % #}"
  style="{% if not small %}font-size: var(--fs-base);{% endif %}">
  <b>{{ name }}</b>
</a>

extensions/templates/extensions/components/badge_tag.html
{% load extensions %}

<a href="{% url "extensions:by-tag" tag_slug=tag.slug %}" title="{{ tag.name }}"
  class="badge badge-tag{% if not small %} badge-lg{% endif %} {{ class }}">
  {{ tag.name }}
</a>

extensions/templates/extensions/components/blender_version.html
{% load i18n common %}

<a
  href="https://www.blender.org/download/releases/{{ version.blender_version_min|version_without_patch|replace:".,-" }}/"
  title="{{ version.blender_version_min }}">Blender {{ version.blender_version_min|version_without_patch }}</a>
{% if is_editable %}
    &mdash;
    <input name="blender_version_max" class="form-control-sm"
      value="{{version.blender_version_max|default_if_none:''}}"
      placeholder="{% trans 'maximum Blender version' %}"
      pattern="^([0-9]+\.[0-9]+\.[0-9]+)?$"
      title="{% trans 'Blender version, e.g. 4.1.0' %}"
    />
    {% for error in form.errors.blender_version_max %}
      <div class="error">{{ error }}</div>
    {% endfor %}
{% else %}
  {% if version.blender_version_max %}
  {% if version.blender_version_max|version_without_patch != version.blender_version_min|version_without_patch %}
    &mdash;
    <a
      href="https://www.blender.org/download/releases/{{ version.blender_version_max|version_without_patch|replace:".,-" }}/"
      title="{{ version.blender_version_max }}">{{ version.blender_version_max|version_without_patch }}</a>
    {% endif %}
  {% else %}
    {% trans 'and newer' %}
  {% endif %}
  <a href="{{ version.extension.get_review_url }}?report_compatibility_issue&version={{ version.version }}#id_message" title="{% trans 'Report compatibility issue' %}"><i class="i-flag"></i></a>
{% endif %}

extensions/templates/extensions/components/card.html
{% load common filters %}
{% with latest=extension.latest_version thumbnail_360p_url=extension.get_previews.0.thumbnail_360p_url %}
  <div class="cards-item">
    <div class="cards-item-content">
      <a href="{{ extension.get_absolute_url }}">
        <div class="cards-item-thumbnail">
          <img alt="{{ extension.name }}" src="{{ thumbnail_360p_url }}" title="{{ extension.name }}">
        </div>
      </a>
      <h3 class="cards-item-title">
        <a href="{{ extension.get_absolute_url }}">{{ extension.name }}</a>
      </h3>
      <div class="cards-item-excerpt">
        <p>
          {{ latest.tagline }}
        </p>
      </div>
      <div class="cards-item-extra">
        <ul>
          <li>
          {% if extension.team %}
            {% with team=extension.team %}
            <a href="{{ team.get_absolute_url }}" title="{{ team.name }}">{{ team.name }}</a>
            {% endwith %}
          {% elif extension.authors.count %}
            {% include "extensions/components/authors.html" %}
          {% endif %}
          </li>
        </ul>

        <ul class="cards-item-extra-rating-stars">
          {% if extension.average_score %}
          <li>
            <a class="align-items-center d-flex" href="{{ extension.get_ratings_url }}">
            {% include "ratings/components/average.html" with score=extension.average_score %}
            ({{ extension.text_ratings_count|int_compact }})
            </a>
          </li>
          {% endif %}

          {% if extension.download_count %}
          <li title="{{ extension.download_count }} downloads">
            <i class="i-download"></i> {{ extension.download_count | int_compact }}
          </li>
          {% endif %}

          {% if show_type %}
          <li class="ms-auto">
            {{ extension.get_type_display }}
          </li>
          {% endif %}
        </ul>

        {% if latest.tags.count %}
        <ul>
          {% for tag in latest.tags.all %}
            <li>
              {% include "extensions/components/badge_tag.html" with small=True version=latest %}
            </li>
          {% endfor %}
        </ul>
        {% endif %}

      </div>
      {# Author/admin tools can be added here in an extending template #}
      {% block admin %}{% endblock admin %}
    </div>
  </div>
{% endwith %}

extensions/templates/extensions/components/categories.html
{% load i18n %}
<div class="card p-3 mb-3">
  <div class="card-header mx-3">
    <h2 class="card-title">{% trans 'Categories' %}</h2>
  </div>
  <div class="card-body m-3">
    <div class="card-text text-center">
      {% for category in categories %}
        {% include "extensions/components/category.html" %}
      {% endfor %}
    </div>
  </div>
</div>

extensions/templates/extensions/components/detail_card_version_permissions.html
<div class="ext-detail-permissions">
  <dt>Permissions</dt>
  {% if version.permissions.all %}
  <dd>This version requests the following:
  <ul>
    {% for p in version.permissions.all %}
    <li>
      <div>
        <i class="i-permission-{{ p.slug }}"></i>
      </div>
      <div>
        <strong>{{ p.name }}</strong>
        <small>{{ p.help }}</small>
      </div>
    </li>
    {% endfor %}
  </ul>
  </dd>
  {% else %}
  <dd>No special permissions required.</dd>
  {% endif %}
</div>

extensions/templates/extensions/components/extension_edit_detail_card.html
{% load i18n common %}

{# Info Summary #}
<section class="ext-detail-info">
  <div class="card p-0">
    {% if is_initial %}
    <div class="badge badge-card badge-info">
      Information retrieved from manifest
    </div>
    {% else %}
    <div class="dl-row px-3 pt-3">
      <div class="dl-col mb-0">
        <dt>{% trans 'Approval Status' %}</dt>
        <dd>{% include "common/components/status.html" with object=extension %}</dd>
      </div>
    </div>
    {% endif %}
    <div class="p-3">
      <dl>
        {% if extension.team or extension.authors.count %}
        <div class="dl-row">
          <div class="dl-col">
          {% if extension.team %}
          {% with team=extension.team %}
          <dt>{% trans 'Team' %}</dt>
          <dd>
            <a href="{{ team.get_absolute_url }}" title="{{ team.name }}">{{ team.name }}</a>
          </dd>
          {% endwith %}
          {% elif extension.authors.count %}
          <dt>Developer{{ extension.authors.count|pluralize }}</dt>
          <dd class="ext-detail-info-authors">
            {% include "extensions/components/authors.html" %}
          </dd>
          {% endif %}
          </div>
        </div>
        {% endif %}

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Name' %}</dt>
            <dd>{{ extension.name }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'ID' %}</dt>
            <dd>{{ extension.extension_id }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Tagline' %}</dt>
            <dd title="{{ version.tagline }}">{{ version.tagline }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Version' %}</dt>
            <dd>
              <a href="{{ extension.get_versions_url }}">
              {{ version.version }}
              </a>
            </dd>
          </div>
          <div class="dl-col">
            <dt>{% trans 'Size' %}</dt>
            <dd>{{ version.file.size_bytes|filesizeformat }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Compatibility' %}</dt>
            <dd>{% include "extensions/components/blender_version.html" with version=version is_editable=is_editable form=form %}</dd>
          </div>
        </div>

        {% if extension.website %}
        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Website' %}</dt>
            <dd>{% include "common/components/external_link.html" with url=extension.website show_path=True %}</dd>
          </div>
        </div>
        {% endif %}

        <div class="dl-row">
          <div class="dl-col">
            <dt>License{{ version.licenses.count|pluralize }}</dt>
            {% for license in version.licenses.all %}
            <dd>
              {% include "common/components/external_link.html" with url=license.url title=license %}
            </dd>
            {% endfor %}
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            {% include "extensions/components/detail_card_version_permissions.html" with version=version %}
          </div>
        </div>

        <div class="dl-row">
          <dd>
            {% if version.tags.count %}
            {% include "extensions/components/tags.html" with small=True version=version %}
            {% else %}
            No tags.
            {% endif %}
          </dd>
        </div>
      </dl>
    </div>
  </div>
</section>

extensions/templates/extensions/components/galleria.html
{% with previews=extension.get_previews %}
<section class="galleria-container" id="galleria-container">
  {% if previews %}
  <div class="galleria-items{% if previews.count > 5 %} is-many{% endif %}{% if previews.count == 1 %} is-single{% endif %}" id="galleria-items">
    {% for preview in previews %}
      {% with thumbnail_1080p_url=preview.thumbnail_1080p_url %}
      <a
        class="galleria-item js-galleria-item-preview galleria-item-type-{{ preview.content_type|slugify|slice:5 }}{% if forloop.first %} is-active{% endif %}"
        href="{{ thumbnail_1080p_url }}"
        {% if 'video' in preview.content_type %}data-galleria-video-url="{{ preview.source.url }}"{% endif %}
        data-galleria-content-type="{{ preview.content_type }}"
        data-galleria-index="{{ forloop.counter }}">

        <img src="{{ thumbnail_1080p_url }}" alt="{{ preview.preview.caption }}">
        </a>
      {% endwith %}
    {% endfor %}
  </div>
  {% else %}
  <div class="galleria-item is-empty">
    <div>
      No preview yet.
      {% if is_maintainer %}
      <a class="btn btn-primary px-5" href="{{ extension.get_manage_url }}#previews">Add a Preview</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</section>
{% endwith %}

extensions/templates/extensions/components/tags.html
{% for tag in version.tags.all %}
{% include "extensions/components/badge_tag.html" %}
{% endfor %}